from helpers import *
import time


def opening_scene(): 
    print('\nYou follow Kaydin through the ship, and soon find yourself in a cramped docking compartment with two other humanoids.')
    dots()
    print('\nThey look a little scary. You wonder what you\'ve gotten yourself into.')
    dots()
    print('\nKaydin: Right, listen up, the Orbital\'s a research vessel: it went dark three rotations ago. We go in quick, we get out quick. Take any valuable tech those lab-rats left behind.')
    dots()
    print('\nKaydin: We get this right, we\'ll be sipping sliders on some distant ocean world with more cred-chips then we know how to spend.')
    dots()
    print('\nThe others cheer. You join in.')
    dots()
    print('\nKaydin: Oh, and a word of caution: we don\'t know why the Orbital went dark. Whatever those lab-rats were cooking up might be what ended up cooking them . . .')
    slow_dots()
    print('There\'s a heavy thunk outside, and a minute later the hatch opens up, leading to the ship you\'re about to salvage.')
    dots()
    print('You follow the others into a dark, empty corridor.')
    dots()
    print('Kaydin: Drax, you and I hit up the cargo-hold. Krug, you\'re on crew cabins.')  
    dots()
    print('Kaydin turns to you.')
    dots()
    print('Kaydin: New kid... see what they\'ve got in their bridge.')
    dots()
    print('Krug: What about survivors?')  
    dots()
    print('Kaydin pats his blaster')
    dots()
    print('Kaydin: You know what to do.')
    slow_dots()
    print()
    print()
    print('You go the opposite direction as the others. At the end of the corridor you come to a door.')
    dots()
    print('There\'s streaks across the battered metal. They look a little like claw marks. Weird.')
    dots()
    print('There\'s a panel to your right. You tap it, and the door slides open.')
    dots()
